FROM node:lts as builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build:server:prod

FROM node:lts-slim as target

WORKDIR /app
COPY --from=builder /app/packages/server/dist /app
COPY --from=builder /app/packages/server/package.json /app
RUN npm install --production

CMD npm run start