name: Build and publish server

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/server/src/**'
    branches:
      - main

jobs:
  build:
    name: Build and publish server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get server version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version packages/server/package.json -r'
      - name: Build docker image
        uses: philips-software/docker-ci-scripts@v4.1.2
        with:
          dockerfile: dockerfile.server
          image-name: visync-server
          tags: latest ${{ steps.version.outputs.value }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io/theasda
          GITHUB_ORGANIZATION: theasda
