name: Build and release extension

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    name: Build and release extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build extension
        run: bun run --bun build:extension
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
          NODE_ENV: production
      - name: Get extension version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version packages/extension/package.json -r'
      - name: Archive extension
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: visync-extension.zip
          path: packages/extension/dist/
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: visync-extension
          path: visync-extension.zip
      - name: Create draft release
        uses: softprops/action-gh-release@v2.2.1
        if: github.event_name != 'pull_request'
        with:
          files: visync-extension.zip
          draft: true
          tag_name: ${{ steps.version.outputs.value }}
          name: Release ${{ steps.version.outputs.value }}
          body: |
            What's new:
            - 
            What's changed:
            - 
            Bug fixes:
            -
