name: Build and release

on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_extension:
    name: Build extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build extension
        run: bun run --bun build:extension
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
          NODE_ENV: production
      - name: Get extension version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version packages/extension/package.json -r'
      - name: Archive extension
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: visync-extension.zip
          path: packages/extension/dist/
      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: visync-extension
          path: visync-extension.zip
      - name: Create draft release
        uses: softprops/action-gh-release@v2.2.1
        if: github.event_name != 'pull_request'
        with:
          files: visync-extension.zip
          draft: true
          tag_name: ${{ steps.version.outputs.value }}
          name: Release ${{ steps.version.outputs.value }}
          body: |
            What's new:
            - 
            What's changed:
            - 
            Bug fixes:
            -
  build_server:
    name: Build and publish server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get server version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version packages/server/package.json -r'
      - name: Determine tags
        id: tags
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAG="pr-${{ github.sha }}"
          else
            TAG="latest ${{ env.value }}"
          fi
      - name: Build and publish docker image
        uses: philips-software/docker-ci-scripts@v5.1.0
        with:
          dockerfile: dockerfile
          image-name: visync-server
          tags: ${{ steps.tags.outputs.tags }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io/theasda
          GITHUB_ORGANIZATION: theasda
  update_pr:
    name: Update PR
    runs-on: ubuntu-latest
    needs:
      - build_extension
      - build_server
    steps:
      - name: Create comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Extension published
          message: |
            #### You can try out extension of this pull request.

            Server is available by ghcr.io/theasda/visync-server:pr-${{ github.sha }}

            Extension is uploaded to pipeline [artifacts](https://github.com/theasda/visync/actions/runs/${{ github.run_id }}#artifacts)
