name: Build and publish server

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    name: Build and publish server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get server version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: 'jq .version packages/server/package.json -r'
      - name: Determine tags
        id: tags
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAG="dev dev-${{ github.run_id }}"
          else
            TAG="latest ${{ env.value }}"
          fi
      - name: Build and publish docker image
        uses: philips-software/docker-ci-scripts@v5.1.0
        with:
          dockerfile: dockerfile
          image-name: visync-server
          tags: ${{ steps.tags.outputs.tags }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io/theasda
          GITHUB_ORGANIZATION: theasda
