name: Deploy server

on:
  workflow_run:
    workflows:
      - Build and publish server
    types:
      - completed

jobs:
  deploy:
    name: Deploy server
    runs-on: ubuntu-latest
    steps:
      - name: Docker compose
        uses: wshihadeh/docker-deployment-action@v1
        with:
          remote_docker_host: ${{ secrets.DOCKER_SSH_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          stack_file_name: docker-compose.yaml
          args: up -d
          pull_images_first: true
